# # for develop
# version: "3"
# services:
#   postgres:
#     image: postgres:14
#     ports:
#     - 5432:5432
#     environment:
#     - POSTGRES_DB=revou
#     - POSTGRES_USER=revou
#     - POSTGRES_PASSWORD=password
#     volumes:
#     - ./postgres-data:/var/lib/postgresql/data
#   pgadmin:
#     image: dpage/pgadmin4
#     environment:
#       - PGADMIN_DEFAULT_EMAIL=dandi@gmail.com
#       - PGADMIN_DEFAULT_PASSWORD=password
#     ports:
#       - 15432:80

# For production
version: '3.9'
services:
  database:
    image: postgres:alpine
    container_name: simerce-database
    hostname: database
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    restart: always
  app:
    image: us-east1-docker.pkg.dev/complete-stock-387402/docker/simerce-app-v1
    container_name: simerce-app
    build: .
    ports:
      - 80:4000
      - 443:4000
      - 4000:4000
    env_file:
      - .env
    depends_on:
      - database
    restart: always
volumes:
  postgres:
